### ISSUE TITLE
Web accessible?

### ISSUE THREAD

**Issue by kalbasit** [albertrdixon/docker-transmission#2]
Thanks Albert for the wonderful Docker image. On which port is the web accessible? I see only 9091 RPC port enabled.

**Comment by kalbasit** [comment]
I hit a dead-end on this. The server is in my home network and I can't reach it from another computer (connect to the same network)

```
$ ssh apollo "docker ps"
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                      NAMES
8344246965b7        albertdixon/transmission   "docker-entry docker-"   22 hours ago        Up 22 hours         0.0.0.0:9091->9091/tcp     transmission
$ transmission-remote 192.168.1.13 -l
[2016-01-12 21:37:47.728 PST] transmission-remote:  (http://192.168.1.13:9091/transmission/rpc/) Timeout was reached
```

**Comment by a-lagopus** [comment]
Hi,
did you proxy the traffic to your container? I believe by default the container is not accessible from local network, since VPN is in a different namespace...

**Comment by albertrdixon** [comment]
That is totally correct. You need to proxy traffic to the container. You can use [jwilder's nginx-proxy](https://github.com/jwilder/nginx-proxy) as a simple drop-in proxy. Just set these environment variables on your transmission container: `VIRTUAL_HOST=your.host  VIRTUAL_PORT=9091`

**Comment by kalbasit** [comment]
I see this is mentioned in the README so I'll close it out. Note that I personally did not verify it as I assigned an old laptop to be a transmission server with PIA enabled. All done outside of docker.
